name: Validate styles

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: pip
      - name: Install dependencies
        run: python -m pip install -Ur requirements.txt

      - run: echo "::add-matcher::.github/matchers/styles.json"
      - name: Run style validation
        run: python -m unittest tests.test_new_styles
      - run: echo "::remove-matcher owner=styles::"
